### ISSUE TITLE
[WARNING]: 0 modules were converted←[0m

### ISSUE THREAD

**Issue by vignaSundar** [magento/code-migration#57] opened 2016-06-18 10:38 UTC
Hi, 
I am facing the problem while working with this toolkit of migrating code from magento1.9.x to magento2

Issue:
[2016-06-18 12:32:02][INFO]: Starting module structure converter
←[0;33m[2016-06-18 12:32:02][WARNING]: 0 modules were converted←[0m
[2016-06-18 12:32:02][INFO]: Ending module structure converter

I checked the log migration.log, below is the output:
[2016-06-18 12:32:02][INFO]: Starting module structure converter
[2016-06-18 12:32:02][WARNING]: 0 modules were converted
[2016-06-18 12:32:02][INFO]: Ending module structure converter

Code:
php migrate.php migrateModuleStructure magento1.9.1 Magento2.1
Trying to migrate code from magento1.9.1  to Magento2.1.
Magento2.1 was empty

This is same issue as https://github.com/magento/code-migration/issues/42, since I couldn't get any answer there I created a new issue.

Could any one help me to get rid of the issue .

Thanks,

**Comment by gordonknoppe** [comment] 2016-07-21 09:47
Duplicate of #42

**Closed by gordonknoppe** 2016-07-21 09:47 UTC
